name: .SP Engine Android Build
on: [push, pull_request, workflow_dispatch] # 只要你提交代码或手动点按钮就会开始编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e # Psych Engine 推荐的 NDK 版本

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install hxCodec
          haxelib run lime setup android
          haxelib run lime setup

      - name: Build Android
        run: haxelib run lime build android -final

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SPEngine-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
